<?php
global $language;
	
$language = array();
	
$language[0] = "";
$language[1] = "zurück";
$language[2] = "Kontakt";
$language[3] = "Bitte füllen Sie alle mit * gekennzeichneten Felder aus.";
$language[4] = "* Pflichtangabe";
$language[5] = "Name";
$language[6] = "Unternehmen";
$language[7] = "Straße";
$language[8] = "PLZ";
$language[9] = "Ort";
$language[10] = "E-Mail-Adresse";
$language[11] = "bitte wählen";
$language[12] = "Ihre Nachricht";
$language[13] = "mehr";
$language[14] = "Senden";
$language[15] = "<h1>Vielen Dank für Ihre Nachricht </h1><p>Wir melden uns schnellstmöglich bei Ihnen</p>";
$language[16] = "suchen";
$language[17] = "Ihr Startpunkt / Ihre Adresse";
$language[18] = "Stadt oder PLZ";
$language[19] = "Route berechnen";
$language[20] = "News";
$language[21] = "Ich stimme zu, dass meine Angaben aus dem Kontaktformular zur Beantwortung meiner Anfrage erhoben und verarbeitet werden. Die Daten werden nach abgeschlossener Bearbeitung Ihrer Anfrage gelöscht.
Hinweis: Sie können Ihre Einwilligung jederzeit für die Zukunft per E-Mail an info@xxxx.de widerrufen.

Detaillierte Informationen zum Umgang mit Nutzerdaten finden Sie in unserer Datenschutzerklärung";
$language[22] = "Kontaktieren";
	?>