<?php
global $language;
	
$language = array();
	
$language[0] = "";
$language[1] = "back";
$language[2] = "Contact";
$language[3] = "Please fill in all of the fields marked with *.";
$language[4] = "* required fields";
$language[5] = "Name";
$language[6] = "Company";
$language[7] = "street";
$language[8] = "ZIP Code";
$language[9] = "city";
$language[10] = "E-Mail";
$language[11] = "please select";
$language[12] = "Your message";
$language[13] = "more";
$language[14] = "send";
$language[15] = "<h1>Thank you for your request</h1><p>We will contact you as soon as possible</p>";
$language[16] = "search";
$language[17] = "Your starting point / your address";
$language[18] = "City or ZIP";
$language[19] = "calculate route";
$language[20] = "News";
$language[21] = "Ich stimme zu, dass meine Angaben aus dem Kontaktformular zur Beantwortung meiner Anfrage erhoben und verarbeitet werden. Die Daten werden nach abgeschlossener Bearbeitung Ihrer Anfrage gelöscht.
Hinweis: Sie können Ihre Einwilligung jederzeit für die Zukunft per E-Mail an info@xxxx.de widerrufen.

Detaillierte Informationen zum Umgang mit Nutzerdaten finden Sie in unserer Datenschutzerklärung";
$language[22] = "";
	?>