<?php  $nav = '
			<li class="nav-item n2 xx2xx"><a href="https://www.morpheus-cms.de/pharmacy/cms/ueber-uns/" class="nav-link"><i class="square rotate-0" id="rotate-square"></i> Über uns</a></li>
			<li class="nav-item n23 dropdown"><a href="https://www.morpheus-cms.de/pharmacy/cms/hofladen/" data-bs-toggle="collapse" aria-expanded="false" class="nav-link n23" ><i class="square rotate-1" id="rotate-square"></i> Hofladen</a>
					<ul class="submenu collapse list-unstyled" id="l27">
						<li class="nav-item2 dd27"><a href="https://www.morpheus-cms.de/pharmacy/cms/hofladen/oeffnungszeiten-hofladen/"" class="nav-link nav-link2 s27 dd27">Öffnungszeiten Hofladen</a></li>
						<li class="nav-item2 dd25"><a href="https://www.morpheus-cms.de/pharmacy/cms/hofladen/obstsortenbestand/"" class="nav-link nav-link2 s25 dd25">Obstsortenbestand</a></li>
						<li class="nav-item2 dd24"><a href="https://www.morpheus-cms.de/pharmacy/cms/hofladen/lexikon/"" class="nav-link nav-link2 s24 dd24">Apfelsortenlexikon</a></li>
					</ul>
			</li>
			<li class="nav-item n31 dropdown"><a href="https://www.morpheus-cms.de/pharmacy/cms/wissenwertes/" data-bs-toggle="collapse" aria-expanded="false" class="nav-link n31" ><i class="square rotate-2" id="rotate-square"></i> Wissenwertes</a>
					<ul class="submenu collapse list-unstyled" id="l32">
						<li class="nav-item2 dd32"><a href="https://www.morpheus-cms.de/pharmacy/cms/wissenwertes/was-ist-apfelwein/"" class="nav-link nav-link2 s32 dd32">Was ist Apfelwein</a></li>
						<li class="nav-item2 dd33"><a href="https://www.morpheus-cms.de/pharmacy/cms/wissenwertes/wie-trinkt-man-apfelwein/"" class="nav-link nav-link2 s33 dd33">Wie trinkt man Apfelwein?</a></li>
					</ul>
			</li>
			<li class="nav-item n20 xx20xx"><a href="https://www.morpheus-cms.de/pharmacy/cms/jobs/" class="nav-link"><i class="square rotate-3" id="rotate-square"></i> Jobs</a></li>
			<li class="nav-item n21 xx21xx"><a href="https://www.morpheus-cms.de/pharmacy/cms/partner/" class="nav-link"><i class="square rotate-4" id="rotate-square"></i> Partner</a></li>
			<li class="nav-item n4 xx4xx"><a href="https://www.morpheus-cms.de/pharmacy/cms/presse/" class="nav-link"><i class="square rotate-5" id="rotate-square"></i> Presse</a></li>
			<li class="nav-item n6 xx6xx"><a href="https://www.morpheus-cms.de/pharmacy/cms/kontakt/" class="nav-link"><i class="square rotate-6" id="rotate-square"></i> Kontakt</a></li>

';
?>