<?php  $nav = '
			<li class="nav-item n7 xx7xx"><a accesskey="7" href="https://www.morpheus-cms.de/pharmacy/cms/ueber-uns/" class="nav-link"><i class="square rotate-0" id="rotate-square"></i> Über uns</a></li>
			<li class="nav-item n8 xx8xx"><a accesskey="6" href="https://www.morpheus-cms.de/pharmacy/cms/faq/" class="nav-link"><i class="square rotate-1" id="rotate-square"></i> FAQ</a></li>
			<li class="nav-item n9 xx9xx"><a accesskey="3" href="https://www.morpheus-cms.de/pharmacy/cms/kontakt/" class="nav-link"><i class="square rotate-2" id="rotate-square"></i> Kontakt</a></li>

';
?>