<?php  $nav = '
			<li class="nav-item n3 xx3xx"><a href="https://www.morpheus-cms.de/shop/wie/" class="nav-link"><i class="square rotate-0" id="rotate-square"></i> wie</a></li>
			<li class="nav-item n2 xx2xx"><a href="https://www.morpheus-cms.de/shop/wer/" class="nav-link"><i class="square rotate-1" id="rotate-square"></i> wer</a></li>
			<li class="nav-item n4 dropdown"><a href="#l9" data-bs-toggle="collapse" aria-expanded="false" class="nav-link n4" ><i class="square rotate-2" id="rotate-square"></i> was</a>
					<ul class="submenu collapse list-unstyled" id="l9">
						<li class="nav-item2 dropdown dd-sub "><a href="https://www.morpheus-cms.de/shop/was/therapie/psychotherapie/"" class="nav-link nav-link2 s9 dropdown dd-sub ">Therapie</a>
							<ul class="sub2menu">
								<li class="nav-item3"><a href="https://www.morpheus-cms.de/shop/was/therapie/psychotherapie/" class="nav-link nav-link3 s11">Psychotherapie</a></li>
								<li class="nav-item3"><a href="https://www.morpheus-cms.de/shop/was/therapie/traumatherapie/" class="nav-link nav-link3 s12">Traumatherapie</a></li>
								<li class="nav-item3"><a href="https://www.morpheus-cms.de/shop/was/therapie/systemische-familientherapie/" class="nav-link nav-link3 s13">Systemische Familientherapie</a>					</ul>
			</li>
</li>
						<li class="nav-item2 dropdown dd-sub "><a href="https://www.morpheus-cms.de/shop/was/diagnostik/leistungsdiagnostik/"" class="nav-link nav-link2 s10 dropdown dd-sub ">Diagnostik</a>
							<ul class="sub2menu">
								<li class="nav-item3"><a href="https://www.morpheus-cms.de/shop/was/diagnostik/leistungsdiagnostik/" class="nav-link nav-link3 s14">Leistungsdiagnostik</a></li>
								<li class="nav-item3"><a href="https://www.morpheus-cms.de/shop/was/diagnostik/diagnostik-von-entwicklungsstoerungen/" class="nav-link nav-link3 s15">Diagnostik von Entwicklungs&shy;störungen</a>					</ul>
			</li>
</li>
						<li class="nav-item2 dropdown dd-sub "><a href="https://www.morpheus-cms.de/shop/was/coaching/eltern-baby-kurse/"" class="nav-link nav-link2 s16 dropdown dd-sub ">Coaching</a>
							<ul class="sub2menu">
								<li class="nav-item3"><a href="https://www.morpheus-cms.de/shop/was/coaching/eltern-baby-kurse/" class="nav-link nav-link3 s17">Eltern-Baby-Kurse</a></li>
							</ul>
						</li>
</li>
					</ul>
			</li>
			<li class="nav-item n5 xx5xx"><a href="https://www.morpheus-cms.de/shop/warum/" class="nav-link"><i class="square rotate-3" id="rotate-square"></i> warum</a></li>

';
?>