
<?php  $output .= '<ul class="sitemap">

		<li class="parent n__3"><a href="https://www.morpheus-cms.de/shop/wie/">wie</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__2"><a href="https://www.morpheus-cms.de/shop/wer/">wer</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__4"><a href="https://www.morpheus-cms.de/shop/was/">was</a>
		 	<ul class="sub-menu3"></li>
</li>
</li>
				<li><a href="https://www.morpheus-cms.de/shop/was/therapie/" title="Therapie">Therapie</a>
				<ul>
</li>
</li>
						<li><a href="https://www.morpheus-cms.de/shop/was/therapie/psychotherapie/" title="Psychotherapie">Psychotherapie</a></li>
</li>
</li>
						<li><a href="https://www.morpheus-cms.de/shop/was/therapie/traumatherapie/" title="Traumatherapie">Traumatherapie</a></li>
</li>
</li>
						<li><a href="https://www.morpheus-cms.de/shop/was/therapie/systemische-familientherapie/" title="Systemische Familientherapie">Systemische Familientherapie</a></li>

				</ul>
			</li>
</li>
</li>
				<li><a href="https://www.morpheus-cms.de/shop/was/diagnostik/" title="Diagnostik">Diagnostik</a>
				<ul>
</li>
</li>
						<li><a href="https://www.morpheus-cms.de/shop/was/diagnostik/leistungsdiagnostik/" title="Leistungsdiagnostik">Leistungsdiagnostik</a></li>
</li>
</li>
						<li><a href="https://www.morpheus-cms.de/shop/was/diagnostik/diagnostik-von-entwicklungsstoerungen/" title="Diagnostik von Entwicklungs&shy;störungen">Diagnostik von Entwicklungs&shy;störungen</a></li>

				</ul>
			</li>
</li>
</li>
				<li><a href="https://www.morpheus-cms.de/shop/was/coaching/" title="Coaching">Coaching</a>
				<ul>
</li>
</li>
						<li><a href="https://www.morpheus-cms.de/shop/was/coaching/eltern-baby-kurse/" title="Eltern-Baby-Kurse">Eltern-Baby-Kurse</a></li>
</ul>
		</li>
</ul>
		</li>

		<li class="parent n__5"><a href="https://www.morpheus-cms.de/shop/warum/">warum</a>
		 	<ul class="sub-menu4"></li>
</ul>
';
?>
</ul>