<?php  $output .= '<ul class="">

				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.morpheus-cms.de/shop/de/wie/">wie</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.morpheus-cms.de/shop/de/wer/">wer</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.morpheus-cms.de/shop/de/was/">was</a></strong></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/therapie/">Therapie</a></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/therapie/psychotherapie/">Psychotherapie</a></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/therapie/traumatherapie/">Traumatherapie</a></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/therapie/systemische-familientherapie/">Systemische Familientherapie</a></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/diagnostik/">Diagnostik</a></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/diagnostik/leistungsdiagnostik/">Leistungsdiagnostik</a></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/diagnostik/diagnostik-von-entwicklungsstoerungen/">Diagnostik von Entwicklungs&shy;störungen</a></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/coaching/">Coaching</a></li>
					<li class="sn"><a href="https://www.morpheus-cms.de/shop/de/was/coaching/eltern-baby-kurse/">Eltern-Baby-Kurse</a></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.morpheus-cms.de/shop/de/warum/">warum</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.morpheus-cms.de/shop/de/impressum/">Impressum</a></strong></li>


				</ul>

				<ul class="nav-child">
					<li class="hn"><strong><a href="https://www.morpheus-cms.de/shop/de/datenschutz/">Datenschutz</a></strong></li>
</ul>'; ?>