
<?php  $structure = '<ul class="sitemap"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__7"><a data-clipboard-text="<a:7:>Link_Name</a>" class="intLink">Über uns</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__8"><a data-clipboard-text="<a:8:>Link_Name</a>" class="intLink">FAQ</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__6"><a data-clipboard-text="<a:6:>Link_Name</a>" class="intLink">Lieferinformationen</a>
		 	<ul class="sub-menu3"></ul>
		</li>

		<li class="parent n__5"><a data-clipboard-text="<a:5:>Link_Name</a>" class="intLink">AGB</a>
		 	<ul class="sub-menu4"></ul>
		</li>

		<li class="parent n__3"><a data-clipboard-text="<a:3:>Link_Name</a>" class="intLink">Impressum</a>
		 	<ul class="sub-menu5"></ul>
		</li>

		<li class="parent n__4"><a data-clipboard-text="<a:4:>Link_Name</a>" class="intLink">Datenschutz</a>
		 	<ul class="sub-menu6"></li>
</ul>
';
?>
</ul>