
<?php  $structure_edit_mode = '<ul class="sitemap_edit"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__7"><a data-clipboard-text="anker:7" class="intLink">Über uns</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__8"><a data-clipboard-text="anker:8" class="intLink">FAQ</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__6"><a data-clipboard-text="anker:6" class="intLink">Lieferinformationen</a>
		 	<ul class="sub-menu3"></ul>
		</li>

		<li class="parent n__5"><a data-clipboard-text="anker:5" class="intLink">AGB</a>
		 	<ul class="sub-menu4"></ul>
		</li>

		<li class="parent n__3"><a data-clipboard-text="anker:3" class="intLink">Impressum</a>
		 	<ul class="sub-menu5"></ul>
		</li>

		<li class="parent n__4"><a data-clipboard-text="anker:4" class="intLink">Datenschutz</a>
		 	<ul class="sub-menu6"></li>
</ul>
';
?>
</ul>