
<?php  $structure = '<ul class="sitemap"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__3"><a data-clipboard-text="<a:3:>Link_Name</a>" class="intLink">wie</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__2"><a data-clipboard-text="<a:2:>Link_Name</a>" class="intLink">wer</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__4"><a data-clipboard-text="<a:4:>Link_Name</a>" class="intLink">was</a>
		 	<ul class="sub-menu3">				<li><a data-clipboard-text="<a:9:>Link_Name</a>" class="intLink">Therapie</a>
				<ul>
						<li><a data-clipboard-text="<a:11:>Link_Name</a>" class="intLink">Psychotherapie</a></li>
						<li><a data-clipboard-text="<a:12:>Link_Name</a>" class="intLink">Traumatherapie</a></li>
						<li><a data-clipboard-text="<a:13:>Link_Name</a>" class="intLink">Systemische Familientherapie</a></li>

				</ul>
			</li>
				<li><a data-clipboard-text="<a:10:>Link_Name</a>" class="intLink">Diagnostik</a>
				<ul>
						<li><a data-clipboard-text="<a:14:>Link_Name</a>" class="intLink">Leistungsdiagnostik</a></li>
						<li><a data-clipboard-text="<a:15:>Link_Name</a>" class="intLink">Diagnostik von Entwicklungs&shy;störungen</a></li>

				</ul>
			</li>
				<li><a data-clipboard-text="<a:16:>Link_Name</a>" class="intLink">Coaching</a>
				<ul>
						<li><a data-clipboard-text="<a:17:>Link_Name</a>" class="intLink">Eltern-Baby-Kurse</a></li>
</ul>
		</li>
</ul>
		</li>

		<li class="parent n__5"><a data-clipboard-text="<a:5:>Link_Name</a>" class="intLink">warum</a>
		 	<ul class="sub-menu4"></li>
		<li><a href="https://www.morpheus-cms.de/shop/de/impressum/" title="impressum"><strong>Impressum</strong></a></li>
			<li><a href="https://www.morpheus-cms.de/shop/de/datenschutz/" title="datenschutz"><strong>Datenschutz</strong></a></li>
	</ul>
';
?>
</ul>