
<?php  $structure_edit_mode = '<ul class="sitemap_edit"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__2"><a data-clipboard-text="anker:2" class="intLink">Über uns</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__23"><a data-clipboard-text="anker:23" class="intLink">Hofladen</a>
		 	<ul class="sub-menu2">				<li><a data-clipboard-text="<anker:27:>" class="intLink">Öffnungszeiten Hofladen</a>				<li><a data-clipboard-text="<anker:25:>" class="intLink">Obstsortenbestand</a>				<li><a data-clipboard-text="<anker:24:>" class="intLink">Apfelsortenlexikon</a></ul>
		</li>

		<li class="parent n__31"><a data-clipboard-text="anker:31" class="intLink">Wissenwertes</a>
		 	<ul class="sub-menu3">				<li><a data-clipboard-text="<anker:32:>" class="intLink">Was ist Apfelwein</a>				<li><a data-clipboard-text="<anker:33:>" class="intLink">Wie trinkt man Apfelwein?</a></ul>
		</li>

		<li class="parent n__20"><a data-clipboard-text="anker:20" class="intLink">Jobs</a>
		 	<ul class="sub-menu4"></ul>
		</li>

		<li class="parent n__21"><a data-clipboard-text="anker:21" class="intLink">Partner</a>
		 	<ul class="sub-menu5"></ul>
		</li>

		<li class="parent n__4"><a data-clipboard-text="anker:4" class="intLink">Presse</a>
		 	<ul class="sub-menu6"></ul>
		</li>

		<li class="parent n__6"><a data-clipboard-text="anker:6" class="intLink">Kontakt</a>
		 	<ul class="sub-menu7"></li>
		<li><a href="https://www.morpheus-cms.de/pharmacy/cms/de/impressum/" title="impressum"><strong>Impressum</strong></a></li>
			<li><a href="https://www.morpheus-cms.de/pharmacy/cms/de/datenschutz/" title="datenschutz"><strong>Datenschutz</strong></a></li>
	</ul>
';
?>
</ul>