
<?php  $structure = '<ul class="sitemap"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__2"><a data-clipboard-text="<a:2:>Link_Name</a>" class="intLink">Über uns</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__23"><a data-clipboard-text="<a:23:>Link_Name</a>" class="intLink">Hofladen</a>
		 	<ul class="sub-menu2">				<li><a data-clipboard-text="<a:27:>Link_Name</a>" class="intLink">Öffnungszeiten Hofladen</a>				<li><a data-clipboard-text="<a:25:>Link_Name</a>" class="intLink">Obstsortenbestand</a>				<li><a data-clipboard-text="<a:24:>Link_Name</a>" class="intLink">Apfelsortenlexikon</a></ul>
		</li>

		<li class="parent n__31"><a data-clipboard-text="<a:31:>Link_Name</a>" class="intLink">Wissenwertes</a>
		 	<ul class="sub-menu3">				<li><a data-clipboard-text="<a:32:>Link_Name</a>" class="intLink">Was ist Apfelwein</a>				<li><a data-clipboard-text="<a:33:>Link_Name</a>" class="intLink">Wie trinkt man Apfelwein?</a></ul>
		</li>

		<li class="parent n__20"><a data-clipboard-text="<a:20:>Link_Name</a>" class="intLink">Jobs</a>
		 	<ul class="sub-menu4"></ul>
		</li>

		<li class="parent n__21"><a data-clipboard-text="<a:21:>Link_Name</a>" class="intLink">Partner</a>
		 	<ul class="sub-menu5"></ul>
		</li>

		<li class="parent n__4"><a data-clipboard-text="<a:4:>Link_Name</a>" class="intLink">Presse</a>
		 	<ul class="sub-menu6"></ul>
		</li>

		<li class="parent n__6"><a data-clipboard-text="<a:6:>Link_Name</a>" class="intLink">Kontakt</a>
		 	<ul class="sub-menu7"></li>
		<li><a href="https://www.morpheus-cms.de/pharmacy/cms/de/impressum/" title="impressum"><strong>Impressum</strong></a></li>
			<li><a href="https://www.morpheus-cms.de/pharmacy/cms/de/datenschutz/" title="datenschutz"><strong>Datenschutz</strong></a></li>
	</ul>
';
?>
</ul>