
<?php  $structure_edit_mode = '<ul class="sitemap_edit"><li class="closeHeader"><i class="fa fa-close"></i></li>

		<li class="parent n__3"><a data-clipboard-text="anker:3" class="intLink">wie</a>
		 	<ul class="sub-menu1"></ul>
		</li>

		<li class="parent n__2"><a data-clipboard-text="anker:2" class="intLink">wer</a>
		 	<ul class="sub-menu2"></ul>
		</li>

		<li class="parent n__4"><a data-clipboard-text="anker:4" class="intLink">was</a>
		 	<ul class="sub-menu3">				<li><a data-clipboard-text="<anker:9:>" class="intLink">Therapie</a>
				<ul>
						<li><a data-clipboard-text="<anker:11:>" class="intLink">Psychotherapie</a></li>
						<li><a data-clipboard-text="<anker:12:>" class="intLink">Traumatherapie</a></li>
						<li><a data-clipboard-text="<anker:13:>" class="intLink">Systemische Familientherapie</a></li>

				</ul>
			</li>
				<li><a data-clipboard-text="<anker:10:>" class="intLink">Diagnostik</a>
				<ul>
						<li><a data-clipboard-text="<anker:14:>" class="intLink">Leistungsdiagnostik</a></li>
						<li><a data-clipboard-text="<anker:15:>" class="intLink">Diagnostik von Entwicklungs&shy;störungen</a></li>

				</ul>
			</li>
				<li><a data-clipboard-text="<anker:16:>" class="intLink">Coaching</a>
				<ul>
						<li><a data-clipboard-text="<anker:17:>" class="intLink">Eltern-Baby-Kurse</a></li>
</ul>
		</li>
</ul>
		</li>

		<li class="parent n__5"><a data-clipboard-text="anker:5" class="intLink">warum</a>
		 	<ul class="sub-menu4"></li>
		<li><a href="https://www.morpheus-cms.de/shop/de/impressum/" title="impressum"><strong>Impressum</strong></a></li>
			<li><a href="https://www.morpheus-cms.de/shop/de/datenschutz/" title="datenschutz"><strong>Datenschutz</strong></a></li>
	</ul>
';
?>
</ul>