<?php

session_start();
include("cms_include.inc");

$arr = array(
array('Alarmsysteme','Jablotron','Kits'),
array('Alarmsysteme','Jablotron','Zentralen'),
array('Alarmsysteme','Jablotron','Bedienteile Bus'),
array('Alarmsysteme','Jablotron','Bedienteile Funk'),
array('Alarmsysteme','Jablotron','Melder Bus'),
array('Alarmsysteme','Jablotron','Melder Funk'),
array('Alarmsysteme','Jablotron','Melder verdrahtet'),
array('Alarmsysteme','Jablotron','Sirenen Bus'),
array('Alarmsysteme','Jablotron','Sirenen Funk'),
array('Alarmsysteme','Jablotron','Sirenen verdrahtet'),
array('Alarmsysteme','Jablotron','Komponenten Bus'),
array('Alarmsysteme','Jablotron','Komponenten Funk'),
array('Alarmsysteme','Jablotron','Komponenten diverse'),
array('Alarmsysteme','Jablotron','Fernbedienungen'),
array('Alarmsysteme','Jablotron','Stromversorgung'),
array('Alarmsysteme','Ajax','Kits'),
array('Alarmsysteme','Ajax','Zentralen / Hubs Bus'),
array('Alarmsysteme','Ajax','Zentralen / Hubs Funk'),
array('Alarmsysteme','Ajax','Bedienteile Bus'),
array('Alarmsysteme','Ajax','Bedienteile Funk'),
array('Alarmsysteme','Ajax','Melder Bus'),
array('Alarmsysteme','Ajax','Melder Funk'),
array('Alarmsysteme','Ajax','Sirenen Bus'),
array('Alarmsysteme','Ajax','Sirenen Funk'),
array('Alarmsysteme','Ajax','Komponenten Bus'),
array('Alarmsysteme','Ajax','Komponenten Funk'),
array('Alarmsysteme','Ajax','Komponenten diverse'),
array('Alarmsysteme','Ajax','Fernbedienungen'),
array('Alarmsysteme','Ajax','Stromversorgung'),
array('Alarmsysteme','Ajax','Urfog Nebelsysteme'),
array('Alarmsysteme','Ajax','Lichtschalter'),
array('Alarmsysteme','Ajax','Luftqualitätsmelder'),
array('Alarmsysteme','Ksenia','Kits'),
array('Alarmsysteme','Ksenia','Zentralen'),
array('Alarmsysteme','Ksenia','Bedienteile Bus'),
array('Alarmsysteme','Ksenia','Bedienteile Funk'),
array('Alarmsysteme','Ksenia','Melder verdrahtet'),
array('Alarmsysteme','Ksenia','Melder Funk'),
array('Alarmsysteme','Ksenia','Sirenen verdrahtet'),
array('Alarmsysteme','Ksenia','Sirenen Funk'),
array('Alarmsysteme','Ksenia','Komponenten Bus'),
array('Alarmsysteme','Ksenia','Komponenten Funk'),
array('Alarmsysteme','Ksenia','Komponenten verdrahtet'),
array('Alarmsysteme','Ksenia','Komponenten diverse'),
array('Alarmsysteme','Ksenia','Fernbedienungen'),
array('Alarmsysteme','Ksenia','Stromversorgung'),
array('Alarmsysteme','Ksenia','Software'),
array('Alarmsysteme','Hikvision','Kits'),
array('Alarmsysteme','Hikvision','Zentralen Bus'),
array('Alarmsysteme','Hikvision','Zentralen Funk'),
array('Alarmsysteme','Hikvision','Bedienteile Bus'),
array('Alarmsysteme','Hikvision','Bedienteile Funk'),
array('Alarmsysteme','Hikvision','Melder Bus'),
array('Alarmsysteme','Hikvision','Melder Funk'),
array('Alarmsysteme','Hikvision','Sirenen Bus'),
array('Alarmsysteme','Hikvision','Sirenen Funk'),
array('Alarmsysteme','Hikvision','Komponenten Bus'),
array('Alarmsysteme','Hikvision','Komponenten Funk'),
array('Alarmsysteme','Hikvision','Komponenten diverse'),
array('Alarmsysteme','Hikvision','Fernbedienungen'),
array('Alarmsysteme','Hikvision','Stromversorgung'),
array('Alarmsysteme','Nox Systems','???'),
array('Alarmsysteme','Ei','Melder Rauch'),
array('Alarmsysteme','Ei','Melder Hitze'),
array('Alarmsysteme','Ei','Melder CO'),
array('Alarmsysteme','Ei','Zubehör'),
array('Alarmsysteme','Optex','Melder Außenbereich IR'),
array('Alarmsysteme','Optex','Melder Außenbereich IR + MW'),
array('Alarmsysteme','Optex','Lichtschranken'),
array('Alarmsysteme','Optex','Melder Innenbereich IR'),
array('Alarmsysteme','Optex','Melder Innenbereich IR + MW'),
array('Alarmsysteme','Optex','Laser Scanner'),
array('Alarmsysteme','Optex','Zubehör'),
array('Alarmsysteme','verdrahtete Komponenten','Melder'),
array('Alarmsysteme','verdrahtete Komponenten','Sirenen'),
array('Alarmsysteme','verdrahtete Komponenten','diverse'),
array('Alarmsysteme','autarke Systeme','???'),
array('Alarmsysteme','Urfog','Nebelsysteme Pumpsysteme'),
array('Alarmsysteme','Urfog','Nebelsysteme Zylindersysteme'),
array('Alarmsysteme','Urfog','Rauchsysteme'),
array('Alarmsysteme','Urfog','Zubehör'),
array('Videoüberwachung','Hikvision','IP Kameras Bullet'),
array('Videoüberwachung','Hikvision','IP Kameras Dome'),
array('Videoüberwachung','Hikvision','IP Kameras Turret'),
array('Videoüberwachung','Hikvision','IP Kameras PTZ'),
array('Videoüberwachung','Hikvision','IP Kameras Cube'),
array('Videoüberwachung','Hikvision','IP Kameras Box'),
array('Videoüberwachung','Hikvision','IP Kameras Kennzeichen'),
array('Videoüberwachung','Hikvision','IP Kameras Thermal'),
array('Videoüberwachung','Hikvision','IP Kameras Spezial'),
array('Videoüberwachung','Hikvision','IP Recorder'),
array('Videoüberwachung','Hikvision','Encoder / Decoder'),
array('Videoüberwachung','Hikvision','Turbo HD Kameras Bullet'),
array('Videoüberwachung','Hikvision','Turbo HD Kameras Dome'),
array('Videoüberwachung','Hikvision','Turbo HD Kameras Turret'),
array('Videoüberwachung','Hikvision','Turbo HD Kameras PTZ'),
array('Videoüberwachung','Hikvision','Turbo HD Kameras Box'),
array('Videoüberwachung','Hikvision','Turbo HD Recorder'),
array('Videoüberwachung','Hikvision','mobile Geräte'),
array('Videoüberwachung','Hikvision','Objektive'),
array('Videoüberwachung','Hikvision','Monitore'),
array('Videoüberwachung','Hikvision','Gehäuse und Halterungen'),
array('Videoüberwachung','Hikvision','Verbindungskomponenten'),
array('Videoüberwachung','Hikvision','Stromversorgung'),
array('Videoüberwachung','Hikvision','Switches'),
array('Videoüberwachung','Hikvision','HikCentral'),
array('Videoüberwachung','Hikvision','Kits'),
array('Videoüberwachung','Hikmicro','Thermal Monokular'),
array('Videoüberwachung','Hikmicro','Thermal Binokular'),
array('Videoüberwachung','Hikmicro','Thermal Clip-On'),
array('Videoüberwachung','Hikmicro','Thermal Handheld'),
array('Videoüberwachung','Hikmicro','Zubehör'),
array('Videoüberwachung','Uniview','IP Kameras Bullet'),
array('Videoüberwachung','Uniview','IP Kameras Dome'),
array('Videoüberwachung','Uniview','IP Kameras Turret'),
array('Videoüberwachung','Uniview','IP Kameras PTZ'),
array('Videoüberwachung','Uniview','IP Kameras Cube'),
array('Videoüberwachung','Uniview','IP Kameras Box'),
array('Videoüberwachung','Uniview','IP Kameras Kennzeichen'),
array('Videoüberwachung','Uniview','IP Kameras Thermal'),
array('Videoüberwachung','Uniview','IP Kameras Spezial'),
array('Videoüberwachung','Uniview','IP Recorder'),
array('Videoüberwachung','Uniview','Encoder / Decoder'),
array('Videoüberwachung','Uniview','HD Analog Kameras Bullet'),
array('Videoüberwachung','Uniview','HD Analog Kameras Dome'),
array('Videoüberwachung','Uniview','HD Analog Kameras Turret'),
array('Videoüberwachung','Uniview','HD Analog Kameras PTZ'),
array('Videoüberwachung','Uniview','HD Analog Kameras Box'),
array('Videoüberwachung','Uniview','HD Analog Recorder'),
array('Videoüberwachung','Uniview','Objektive'),
array('Videoüberwachung','Uniview','Monitore'),
array('Videoüberwachung','Uniview','Gehäuse und Halterungen'),
array('Videoüberwachung','Uniview','Verbindungskomponenten'),
array('Videoüberwachung','Uniview','Stromversorgung'),
array('Videoüberwachung','Uniview','Switches'),
array('Videoüberwachung','Uniview','Kits'),
array('Videoüberwachung','idis','Kits'),
array('Bodycams','Zepcam','Kameras'),
array('Bodycams','Zepcam','Docking Stations'),
array('Bodycams','Zepcam','Zubehör'),
array('Bodycams','Zepcam','Services'),
array('Bodycams','Reveal Media','Kameras'),
array('Bodycams','Reveal Media','Docking Stations'),
array('Bodycams','Reveal Media','Zubehör'),
array('Bodycams','Hikvision','Kameras'),
array('Bodycams','Hikvision','Docking Stations'),
array('Bodycams','Hikvision','Zubehör'),
array('Medientechnik','Hikvision','interaktive Monitore'),
array('Medientechnik','Hikvision','OPS PC Module'),
array('Medientechnik','Hikvision','Digital Signage'),
array('Medientechnik','Hikvision','Webcams'),
array('Medientechnik','Hikvision','Zubehör'),
array('Medientechnik','Uniview','interaktive Monitore'),
array('Medientechnik','Uniview','OPS PC Module'),
array('Medientechnik','Uniview','Digital Signage'),
array('Medientechnik','Uniview','Zubehör'),
array('Sprechanlagen','Hikvision','IP Kits'),
array('Sprechanlagen','Hikvision','IP Außenstationen'),
array('Sprechanlagen','Hikvision','IP Innenstationen'),
array('Sprechanlagen','Hikvision','IP Zubehör'),
array('Sprechanlagen','Hikvision','2-Draht Kits'),
array('Sprechanlagen','Hikvision','2-Draht Außenstationen'),
array('Sprechanlagen','Hikvision','2-Draht Innenstationen'),
array('Sprechanlagen','Hikvision','2-Draht Zubehör'),
array('Sprechanlagen','Hikvision','allgemeines Zubehör'),
array('Sprechanlagen','Hikvision','SIP Telefone'),
array('Zutrittskontrolle','Hikvision','Terminals'),
array('Zutrittskontrolle','Hikvision','RFID Komponenten'),
array('Zutrittskontrolle','Hikvision','Zentralen'),
array('Zutrittskontrolle','Uniview','Terminals'),
array('Zutrittskontrolle','Uniview','Zubehör'),
array('Zutrittskontrolle','Elock2','Terminals'),
array('Zutrittskontrolle','Elock2','RFID Komponenten'),
array('Zutrittskontrolle','Elock2','Zentralen'),
array('Schließsysteme','smartLOXX','Zylinder'),
array('Schließsysteme','smartLOXX','Zubehör'),
array('Schließsysteme','Elock2','Zylinder'),
array('Schließsysteme','Elock2','Zubehör'),
array('Schließsysteme','Hikvision','Schließsysteme'),
array('Schließsysteme','Hikvision','Zubehör'),
array('Energietechnik','Uniview','Energiespeichersysteme'),
array('Energietechnik','Uniview','Zubehör'),
);

$newTable = "morp_products";

$table 		= 'morp_product_einzeln';
$tid 		= 'peID';
$nameField 	= "produkt";

$table2 	= 'morp_product_company';
$tid2 		= 'pcID';
$nameField2	= "company";

$table3 	= 'morp_product_wg';
$tid3 		= 'wgID';
$nameField3	= "wg";
$x = 0;
foreach ($arr as $array) {
	$x++;
	$id1 = get_db_field($array[0], $tid3, $table3, $nameField3);
	$id2 = get_db_field($array[1], $tid2, $table2, $nameField2);
	$id3 = get_db_field($array[2], $tid, $table, $nameField);
	echo $x.' ::: '.$array[0].' - '.$id1.' - '.$array[1].' - '.$id2.' - '.$array[2].' - '.$id3.'<br>';
	
// 	echo $sql = "INSERT $newTable SET $tid3=$id1 , $tid2=$id2 , $tid=$id3 ";
// 	$res = safe_query($sql);
// 	echo br();
}